cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-versions'
tap 'caskroom/fonts'

brew 'ack'
brew 'awscli'
brew 'coreutils'
brew 'fasd'
brew 'git-extras'
brew 'git-fixup'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'jsonpp'
brew 'n'
brew 'rust-init'
brew 'openssl'
brew 'readline'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '1password'
cask 'aerial'
cask 'atom'
cask 'docker'
cask 'firefox'
cask 'font-hack-nerd-font'
cask 'google-backup-and-sync'
cask 'google-chrome-beta'
cask 'iterm2'
cask 'postico'
cask 'postman'
cask 'sequel-pro'
cask 'slack'
cask 'spotify'
cask 'transmission'
cask 'tunnelblick'
cask 'tunnelbear'
cask 'vlc'
cask 'zoomus'
