version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    working_directory: ~/.dotfiles
    steps:
      - checkout
      - run:
          name: "Install dotfiles"
          command: |
            cd ~/.dotfiles
            ./bin/dot

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          # run the workflow every day at 12am
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
