
# Customise the Powerlevel9k prompts
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_flame context dir vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# Add the custom flame prompt segment
export POWERLEVEL9K_CUSTOM_FLAME="echo -n $'\uF490'"
export POWERLEVEL9K_CUSTOM_FLAME_FOREGROUND="black"
export POWERLEVEL9K_CUSTOM_FLAME_BACKGROUND="white"

# Add custom format and colors to context segment.
export POWERLEVEL9K_CONTEXT_TEMPLATE="%n"
export POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="white"
export POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="cyan"

export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
export POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
export POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\uf054 "
