name: Test macOS

on:
  push:
    paths-ignore:
      - "README.md"

  workflow_dispatch:

  # run the workflow every day at 12am
  schedule:
    - cron: "0 0 * * *"

jobs:
  test_bin_dot:
    name: macOS ${{ matrix.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners
        os: [macos-15]
        include:
          - os: macos-15
            name: Sequoia
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .dotfiles

      - name: Install dotfiles
        env:
          DOTFILES: ${{ github.workspace }}/.dotfiles
        run: |
          cd "$DOTFILES"
          ./bin/dot
