name: Test macOS

on:
  push:
    paths-ignore:
      - ".circleci/**"
      - "README.md"

  # run the workflow every day at 12am
  schedule:
    - cron: "0 0 * * *"

jobs:
  test_bin_dot:
    name: macOS ${{ matrix.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.15]
        include:
          - os: macOS-10.15
            name: Catalina
          # macOS 11.0 image was temporarily disabled for public pools
          # https://github.com/actions/virtual-environments/issues/2486
          # - os: macOS-11.0
          #   name: Big Sur
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .dotfiles

      - name: Workarounds (cleanup environment)
        run: |
          brew uninstall go@1.15
          rm -rf /usr/local/etc/openssl
          rm -rf /usr/local/etc/openssl@1.1
          rm -rf /usr/local/bin/aws
          rm -rf /usr/local/bin/aws_completer
          rm -rf /usr/local/bin/node
          rm -rf /usr/local/bin/npm

      - name: Install dotfiles
        run: |
          export DOTFILES=$HOME/work/dotfiles/dotfiles/.dotfiles
          cd .dotfiles
          ./bin/dot
